# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["bbenvenuti@fastly.com"]
description = "proxy for rt stats without a key"
language = "javascript"
manifest_version = 3
name = "reverse-rt-proxy"
service_id = "kubIkc9LfJ6YgRxnKv3eD3"

[local_server]

  [local_server.backends]

    [local_server.backends.rt]
      url = "https://rt.fastly.com"

  [local_server.secret_stores]

    tokens = [{ key = "bradbenvenuti", file = "token.txt" }]

[scripts]
  build = "npm run build"

[setup]

  [setup.backends]

    [setup.backends.rt]
      address = "rt.fastly.com"
      description = "rt stats"
      port = 443
